/**
 * 可愛頭像庫 — 動物、海洋生物、趣味角色（emoji）
 */
(function (global) {
  var CATEGORIES = [
    { id: "all", labelKey: "flow.avatarCatAll" },
    { id: "land", labelKey: "flow.avatarCatLand" },
    { id: "sea", labelKey: "flow.avatarCatSea" },
    { id: "sky", labelKey: "flow.avatarCatSky" },
    { id: "fun", labelKey: "flow.avatarCatFun" },
    { id: "cosmic", labelKey: "flow.avatarCatCosmic" },
    { id: "epic", labelKey: "flow.avatarCatEpic" },
    { id: "horror", labelKey: "flow.avatarCatHorror" },
    { id: "alien", labelKey: "flow.avatarCatAlien" },
  ];

  /** @type {{ id: string, emoji: string, cats: string[] }[]} */
  var AVATARS = [
    { id: "frog", emoji: "🐸", cats: ["land", "fun"] },
    { id: "bear", emoji: "🐻", cats: ["land"] },
    { id: "panda", emoji: "🐼", cats: ["land"] },
    { id: "koala", emoji: "🐨", cats: ["land"] },
    { id: "tiger", emoji: "🐯", cats: ["land"] },
    { id: "lion", emoji: "🦁", cats: ["land"] },
    { id: "cow", emoji: "🐮", cats: ["land"] },
    { id: "pig", emoji: "🐷", cats: ["land"] },
    { id: "pig_nose", emoji: "🐽", cats: ["land", "fun"] },
    { id: "monkey", emoji: "🐵", cats: ["land"] },
    { id: "see_no", emoji: "🙈", cats: ["land", "fun"] },
    { id: "hear_no", emoji: "🙉", cats: ["land", "fun"] },
    { id: "speak_no", emoji: "🙊", cats: ["land", "fun"] },
    { id: "gorilla", emoji: "🦍", cats: ["land"] },
    { id: "orangutan", emoji: "🦧", cats: ["land"] },
    { id: "dog", emoji: "🐕", cats: ["land"] },
    { id: "poodle", emoji: "🐩", cats: ["land"] },
    { id: "guide_dog", emoji: "🦮", cats: ["land"] },
    { id: "service_dog", emoji: "🐕‍🦺", cats: ["land"] },
    { id: "cat", emoji: "🐈", cats: ["land"] },
    { id: "black_cat", emoji: "🐈‍⬛", cats: ["land"] },
    { id: "rooster", emoji: "🐓", cats: ["land", "sky"] },
    { id: "chicken", emoji: "🐔", cats: ["land"] },
    { id: "penguin", emoji: "🐧", cats: ["land", "sea"] },
    { id: "bird", emoji: "🐦", cats: ["sky"] },
    { id: "duck", emoji: "🦆", cats: ["sky", "land"] },
    { id: "eagle", emoji: "🦅", cats: ["sky"] },
    { id: "owl", emoji: "🦉", cats: ["sky", "land"] },
    { id: "bat", emoji: "🦇", cats: ["sky", "fun"] },
    { id: "wolf", emoji: "🐺", cats: ["land"] },
    { id: "fox", emoji: "🦊", cats: ["land"] },
    { id: "raccoon", emoji: "🦝", cats: ["land"] },
    { id: "boar", emoji: "🐗", cats: ["land"] },
    { id: "deer", emoji: "🦌", cats: ["land"] },
    { id: "horse", emoji: "🐴", cats: ["land"] },
    { id: "unicorn", emoji: "🦄", cats: ["land", "fun"] },
    { id: "zebra", emoji: "🦓", cats: ["land"] },
    { id: "giraffe", emoji: "🦒", cats: ["land"] },
    { id: "elephant", emoji: "🐘", cats: ["land"] },
    { id: "rhino", emoji: "🦏", cats: ["land"] },
    { id: "hippo", emoji: "🦛", cats: ["land"] },
    { id: "camel", emoji: "🐫", cats: ["land"] },
    { id: "llama", emoji: "🦙", cats: ["land", "fun"] },
    { id: "goat", emoji: "🐐", cats: ["land"] },
    { id: "sheep", emoji: "🐑", cats: ["land"] },
    { id: "rabbit", emoji: "🐰", cats: ["land"] },
    { id: "hamster", emoji: "🐹", cats: ["land"] },
    { id: "mouse", emoji: "🐭", cats: ["land"] },
    { id: "rat", emoji: "🐀", cats: ["land"] },
    { id: "chipmunk", emoji: "🐿️", cats: ["land"] },
    { id: "beaver", emoji: "🦫", cats: ["land"] },
    { id: "hedgehog", emoji: "🦔", cats: ["land"] },
    { id: "kangaroo", emoji: "🦘", cats: ["land"] },
    { id: "badger", emoji: "🦡", cats: ["land"] },
    { id: "sloth", emoji: "🦥", cats: ["land", "fun"] },
    { id: "otter", emoji: "🦦", cats: ["land", "sea"] },
    { id: "skunk", emoji: "🦨", cats: ["land"] },
    { id: "bison", emoji: "🦬", cats: ["land"] },
    { id: "turtle", emoji: "🐢", cats: ["land", "sea"] },
    { id: "croc", emoji: "🐊", cats: ["land"] },
    { id: "snake", emoji: "🐍", cats: ["land"] },
    { id: "lizard", emoji: "🦎", cats: ["land"] },
    { id: "dragon", emoji: "🐉", cats: ["fun", "land"] },
    { id: "dragon_face", emoji: "🐲", cats: ["fun"] },
    { id: "dino", emoji: "🦕", cats: ["land", "fun"] },
    { id: "dino2", emoji: "🦖", cats: ["land", "fun"] },
    { id: "octopus", emoji: "🐙", cats: ["sea"] },
    { id: "squid", emoji: "🦑", cats: ["sea"] },
    { id: "jelly", emoji: "🪼", cats: ["sea"] },
    { id: "crab", emoji: "🦀", cats: ["sea"] },
    { id: "lobster", emoji: "🦞", cats: ["sea"] },
    { id: "shrimp", emoji: "🦐", cats: ["sea"] },
    { id: "fish", emoji: "🐟", cats: ["sea"] },
    { id: "tropical", emoji: "🐠", cats: ["sea"] },
    { id: "blowfish", emoji: "🐡", cats: ["sea", "fun"] },
    { id: "shark", emoji: "🦈", cats: ["sea"] },
    { id: "dolphin", emoji: "🐬", cats: ["sea"] },
    { id: "whale", emoji: "🐳", cats: ["sea"] },
    { id: "whale2", emoji: "🐋", cats: ["sea"] },
    { id: "seal", emoji: "🦭", cats: ["sea"] },
    { id: "shell", emoji: "🐚", cats: ["sea"] },
    { id: "coral", emoji: "🪸", cats: ["sea"] },
    { id: "swan", emoji: "🦢", cats: ["sky", "sea"] },
    { id: "peacock", emoji: "🦚", cats: ["sky", "land"] },
    { id: "parrot", emoji: "🦜", cats: ["sky"] },
    { id: "flamingo", emoji: "🦩", cats: ["sky", "land"] },
    { id: "dove", emoji: "🕊️", cats: ["sky"] },
    { id: "bee", emoji: "🐝", cats: ["sky", "land"] },
    { id: "butterfly", emoji: "🦋", cats: ["sky", "fun"] },
    { id: "ladybug", emoji: "🐞", cats: ["land", "fun"] },
    { id: "snail", emoji: "🐌", cats: ["land"] },
    { id: "bug", emoji: "🐛", cats: ["land"] },
    { id: "ant", emoji: "🐜", cats: ["land"] },
    { id: "spider", emoji: "🕷️", cats: ["land", "fun"] },
    { id: "scorpion", emoji: "🦂", cats: ["land"] },
    { id: "alien", emoji: "👽", cats: ["fun"] },
    { id: "robot", emoji: "🤖", cats: ["fun"] },
    { id: "ghost", emoji: "👻", cats: ["fun"] },
    { id: "pumpkin", emoji: "🎃", cats: ["fun"] },
    { id: "clown", emoji: "🤡", cats: ["fun"] },
    { id: "fairy", emoji: "🧚", cats: ["fun"] },
    { id: "wizard", emoji: "🧙", cats: ["fun"] },
    { id: "superhero", emoji: "🦸", cats: ["fun"] },
    { id: "ninja", emoji: "🥷", cats: ["fun"] },
    { id: "teddy", emoji: "🧸", cats: ["fun"] },
    { id: "party", emoji: "🥳", cats: ["fun"] },
    { id: "star", emoji: "🌟", cats: ["fun"] },
    { id: "rainbow", emoji: "🌈", cats: ["fun"] },
    { id: "moon", emoji: "🌙", cats: ["fun", "sky"] },
    { id: "sun", emoji: "☀️", cats: ["fun", "sky"] },
    { id: "cloud", emoji: "⛅", cats: ["fun", "sky"] },
    { id: "rain", emoji: "🌧️", cats: ["fun"] },
    { id: "lightning", emoji: "⚡", cats: ["fun"] },
    { id: "fire", emoji: "🔥", cats: ["fun"] },
    { id: "gem", emoji: "💎", cats: ["fun"] },
    { id: "clover", emoji: "🍀", cats: ["fun"] },
    { id: "mushroom", emoji: "🍄", cats: ["fun", "land"] },
    { id: "cherry_blossom", emoji: "🌸", cats: ["fun"] },
    { id: "sunflower", emoji: "🌻", cats: ["fun"] },
    { id: "rose", emoji: "🌹", cats: ["fun"] },
    { id: "balloon", emoji: "🎈", cats: ["fun"] },
    { id: "gift", emoji: "🎁", cats: ["fun"] },
    { id: "art", emoji: "🎨", cats: ["fun"] },
    { id: "music", emoji: "🎵", cats: ["fun"] },
    { id: "game", emoji: "🎮", cats: ["fun"] },
    { id: "rocket", emoji: "🚀", cats: ["fun", "sky"] },
    { id: "comet", emoji: "☄️", cats: ["fun", "sky"] },
    { id: "satellite", emoji: "🛸", cats: ["fun", "sky"] },
    { id: "ringed", emoji: "🪐", cats: ["cosmic", "sky"] },
    { id: "milky", emoji: "🌌", cats: ["cosmic"] },
    { id: "telescope", emoji: "🔭", cats: ["cosmic", "sky"] },
    { id: "shooting", emoji: "🌠", cats: ["cosmic", "sky"] },
    { id: "sparkles", emoji: "✨", cats: ["cosmic", "epic"] },
    { id: "dizzy", emoji: "💫", cats: ["cosmic", "epic"] },
    { id: "crystal_ball", emoji: "🔮", cats: ["cosmic", "epic", "horror"] },
    { id: "volcano", emoji: "🌋", cats: ["epic", "land"] },
    { id: "mountain", emoji: "🏔️", cats: ["epic", "land"] },
    { id: "castle", emoji: "🏰", cats: ["epic"] },
    { id: "crown", emoji: "👑", cats: ["epic"] },
    { id: "trophy", emoji: "🏆", cats: ["epic", "fun"] },
    { id: "medal", emoji: "🏅", cats: ["epic"] },
    { id: "eagle_epic", emoji: "🦅", cats: ["epic", "sky"] },
    { id: "dragon_epic", emoji: "🐲", cats: ["epic", "fun"] },
    { id: "phoenix", emoji: "🔥", cats: ["epic", "fun"] },
    { id: "skull", emoji: "💀", cats: ["horror"] },
    { id: "skull_cross", emoji: "☠️", cats: ["horror"] },
    { id: "zombie", emoji: "🧟", cats: ["horror", "fun"] },
    { id: "vampire", emoji: "🧛", cats: ["horror", "fun"] },
    { id: "genie", emoji: "🧞", cats: ["horror", "epic", "fun"] },
    { id: "ogre", emoji: "👹", cats: ["horror", "fun"] },
    { id: "goblin", emoji: "👺", cats: ["horror", "fun"] },
    { id: "ghost_horror", emoji: "👻", cats: ["horror", "fun"] },
    { id: "jack", emoji: "🎃", cats: ["horror", "fun"] },
    { id: "spider_h", emoji: "🕸️", cats: ["horror"] },
    { id: "alien_face", emoji: "👽", cats: ["alien", "fun"] },
    { id: "ufo", emoji: "🛸", cats: ["alien", "cosmic", "fun"] },
    { id: "invader", emoji: "👾", cats: ["alien", "fun"] },
    { id: "robot_alien", emoji: "🤖", cats: ["alien", "fun"] },
    { id: "saturn", emoji: "🪐", cats: ["alien", "cosmic"] },
    { id: "dna", emoji: "🧬", cats: ["alien", "cosmic"] },
    { id: "microbe", emoji: "🦠", cats: ["alien"] },
    { id: "test_tube", emoji: "🧪", cats: ["alien", "cosmic"] },
    { id: "prism", emoji: "🌈", cats: ["cosmic", "epic", "fun"] },
    { id: "hundred", emoji: "💯", cats: ["epic", "fun"] },
    { id: "boom", emoji: "💥", cats: ["epic", "fun"] },
    { id: "collision", emoji: "💥", cats: ["cosmic"] },
    { id: "cyclone", emoji: "🌀", cats: ["cosmic", "sky"] },
    { id: "snowflake", emoji: "❄️", cats: ["cosmic", "sky"] },
    { id: "comet2", emoji: "☄️", cats: ["cosmic", "alien"] },
  ];

  function listByCategory(catId) {
    if (!catId || catId === "all") return AVATARS.slice();
    return AVATARS.filter(function (a) {
      return a.cats.indexOf(catId) >= 0;
    });
  }

  function byId(id) {
    for (var i = 0; i < AVATARS.length; i++) {
      if (AVATARS[i].id === id) return AVATARS[i];
    }
    return null;
  }

  function isValidEmoji(emoji) {
    if (!emoji) return false;
    return AVATARS.some(function (a) {
      return a.emoji === emoji;
    });
  }

  global.RNFAvatarPool = {
    CATEGORIES: CATEGORIES,
    AVATARS: AVATARS,
    listByCategory: listByCategory,
    byId: byId,
    isValidEmoji: isValidEmoji,
    count: AVATARS.length,
  };
})(window);
